"""added running_time integer variable to song data

Revision ID: 7dafc73211f9
Revises: 8c260fdeb1f8
Create Date: 2023-04-06 11:57:08.245216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dafc73211f9'
down_revision = '8c260fdeb1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('running_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('running_time')

    # ### end Alembic commands ###
