"""Add likes(int) column

Revision ID: 8c260fdeb1f8
Revises: c071c957e25e
Create Date: 2023-03-14 09:35:41.251003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c260fdeb1f8'
down_revision = 'c071c957e25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
